package chatting_program;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Base64;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;

public class Server implements Runnable {
	
	ServerSocket serversocket;
	Socket socket;
	BufferedReader reader1, reader2;
	PrintWriter writer;
	Thread t1, t2;
	volatile String in = "";
	volatile String out = "";
	static int PORT = 5678;
	KeyPair keypair_RSA = null;
	PrivateKey priv_RSA = null;
	PublicKey pub_RSA = null;
	boolean start1 = true;
	PublicKey pub = null;
	ObjectOutputStream outO = null;
	OutputStream os = null;
	ObjectInputStream inO = null;
	InputStream is = null;
	SecretKey sKey = null;
	byte[] encrypted_AESkey = null;
	static String iv = "0987654321654321";
	
	
	
	public static void main(String[] args) {
		new Server();
	}
	
	
	public Server() 
	{
		/**
		 * Create RSA Key Pair
		 */
		keypair_RSA = generate_RSA_key();
		pub_RSA = keypair_RSA.getPublic();
		priv_RSA = keypair_RSA.getPrivate();
		
		try {
			
			//Thread for write
			t1 = new Thread(this);
			
			//Thread for read
			t2 = new Thread(this);
			
			serversocket = new ServerSocket(PORT);
			
			System.out.println("Connecting...");			
			socket = serversocket.accept();
			
			System.out.println("##Connection success##\n");
			
			t1.start();
			t2.start();
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	
	public void run()
	{
		try {			
			if(Thread.currentThread() == t1) {
				/*
				 * Writing Thread
				 */
				
				//send RSA public key to client
				if(start1 = true) {
					os = socket.getOutputStream();
					outO = new ObjectOutputStream(os);
					outO.writeObject(pub_RSA);
					outO.flush();
					
					//Print RSA KeyPair
					System.out.println("[RSA KeyPair info generated by Server]");
					System.out.println(pub_RSA);
					System.out.println(priv_RSA + "\n");
					
					start1 = false;
				}
				
				while(!in.equals("exit")) {
					//Writing Chat
					
					reader1 = new BufferedReader(new InputStreamReader(System.in));
					writer = new PrintWriter(socket.getOutputStream(), true);
					
					//Add time stamp to entered message
					Long timeStamp = System.currentTimeMillis(); 
			        SimpleDateFormat sdf=new SimpleDateFormat("[yyyy-MM-dd HH:mm:ss]");
			        String sd = sdf.format(new Date(Long.parseLong(String.valueOf(timeStamp)))); 
					in = reader1.readLine();
					String send = "\"" + in +"\"" + " " + sd;
					
					//Encrypt with AES256
					String send_encrypt = Encrypt_AES(send, sKey);
					
					//Send Encrypted Message to Client
				    writer.println(send_encrypt);
				    
				}
			} else {
				/*
				 * Reading Thread
				 */
				
				while(true) {
					
					if(encrypted_AESkey == null) {
						
						is = socket.getInputStream();
						inO = new ObjectInputStream(is);
						encrypted_AESkey = (byte[])inO.readObject();
						
						
					} else {
						
						
						sKey = Decrypt_RSA(encrypted_AESkey, priv_RSA);
						
						//print AES secretKey
						System.out.println("[AES SecretKey info From Client]");
						System.out.println(sKey + "\n");
						
						break;
					}
				}

				while(!out.equals("exit")) {
					//Reading Chat
					
					reader2 = new BufferedReader(new InputStreamReader(socket.getInputStream()));
					out = reader2.readLine();
					
					String decrypted_out = Decrypt_AES(out, sKey);
					
					System.out.println("[From Server]" + decrypted_out);
					System.out.println("[Encrypted Message] \"" + out + "\" + \n");
					
				}
			}
			
			writer.close();
			reader1.close();
			reader2.close();
			outO.close();
			
			socket.close();
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	
	public static KeyPair generate_RSA_key() {
		
		System.out.println("[Creating RSA Key Pair...]");
		
		KeyPair keyPair = null;
		
		try {
		    SecureRandom sr = new SecureRandom();
		    KeyPairGenerator generator;
		
		    generator = KeyPairGenerator.getInstance("RSA");
		    generator.initialize(2048, sr);
		
		    keyPair = generator.generateKeyPair();
		
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return keyPair;
	}
	
	
	public static SecretKey Decrypt_RSA(byte[] encrypted, PrivateKey privateKey) {
		
		String decrypted = null;
		SecretKey key = null;
		
		try {
			
			Cipher cipher = Cipher.getInstance("RSA");
			
			cipher.init(Cipher.DECRYPT_MODE, privateKey);
			
			key = new SecretKeySpec(cipher.doFinal(encrypted), "AES");
			
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return key;
	}
		
	
	public static String Encrypt_AES(String plaintext, SecretKey key)
	{
		String result = null;
		
		try {
		    
			Cipher c = Cipher.getInstance("AES/CBC/PKCS5Padding");
		    c.init(Cipher.ENCRYPT_MODE, key, new IvParameterSpec(iv.getBytes()));
		 
		    byte[] encrypted = c.doFinal(plaintext.getBytes("UTF-8"));
		    result = new String(Base64.getEncoder().encode(encrypted));
		 
		    
		} catch (Exception e) {
			e.printStackTrace();
		}
		return result;
	}
	
	
	public static String Decrypt_AES(String ciphertext, SecretKey key)
	{
		String result = null;
		
		try {
		    
		    Cipher c = Cipher.getInstance("AES/CBC/PKCS5Padding");
		    c.init(Cipher.DECRYPT_MODE, key, new IvParameterSpec(iv.getBytes("UTF-8")));
		    
		    byte[] decrypted = Base64.getDecoder().decode(ciphertext.getBytes("UTF-8"));
		    result = new String(c.doFinal(decrypted), "UTF-8");
		 
		    
		} catch (Exception e) {
			e.printStackTrace();
		}
		return result;
	}
	
}